// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjtckvdyykemhxqalxgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqdGNrdmR5eWtlbWh4cWFseGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTEzMzEsImV4cCI6MjA1OTAyNzMzMX0.ysjhAyfTcX4azpgphlOBEbBtmMK50Fk2vSDwyqY8uIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);